name: 'Azure Function Time'
description: 'Connect to an Azure Function to get the current date and time'
inputs:
  function-url:
    description: 'URL of the Azure Function endpoint'
    required: true
outputs:
  currentDateTime:
    description: 'The current date and time retrieved from the Azure Function'
runs:
  using: 'node20'
  main: 'index.js'
